version: '3'
services:
  backcliente:
    build: 
      context: ./BackCliente
      dockerfile: Dockerfile
    ports:
      - 5002:5002

  backproduto:
    build: 
      context: ./BackProduto
      dockerfile: Dockerfile
    ports:
      - 5001:5001

  backcompra:
    build: 
      context: ./BackCompra
      dockerfile: Dockerfile
    ports:
      - 5003:5003

  front:
    build: 
      context: ./Front
      dockerfile: Dockerfile
    ports:
      - 80:80
